export const GET_COURSES = "GET_ALL_COURSES";
export const COURSE_SUCESS = "COURSE_SUCESS";
export const RESET_FLAGS = "RESET_FLAGS";
export const COURSE_FAIL = "COURSE_FAIL";
export const GET_SINGLE_COURSES = "GET_SINGLE_COURSES";
