export const ADD_SECTION_SUCESS = "ADD_SECTION_SUCESS";
export const SET_LOAD_SECTION = "SET_LOAD_SECTION";
export const RESET_FLAGS_SECTION = "RESET_FLAGS_SECTION";
export const ADD_SECTION_FAIL = "ADD_SECTION_FAIL";
